on:
  workflow_dispatch:

jobs:
  add_help_wanted_labels:
    runs-on: ubuntu-latest
    name: Add help wanted labels
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./add-label-to-cards/
        id: add-help-wanted-labels
        name: Add help wanted labels
        with:
          columns_labels: >
            [
              {
                "column_name": "To do",
                "labels": ["Help Wanted"],
                "project_name": "Test"
              },
              {
                "column_name": "To do",
                "labels": ["Help Wanted", null, 12, "test"],
                "project_name": "Test"
              },
              {
                "column_name": "To do",
                "project_name": "Test"
              },
              {
                "column_name": "To do",
                "labels": null,
                "project_name": "Test"
              },
              {
                "column_name": "To do",
                "labels": [3],
                "project_name": "Test"
              },
              {
                "column_name": "",
                "labels": ["Empty Str Columns"],
                "project_name": "Test"
              },
              {
                "labels": ["Not Enough Column Info"],
                "project_name": "Test"
              },
              {
                "column_id" : 1234567,
                "column_name": "To do",
                "labels": ["All column identifiers"],
                "project_name": "Test"
              },
              {
                "column_id" : null,
                "column_name": "To do",
                "labels": ["Partially invalid column ids"],
                "project_name": "Test"
              }
            ]
          token: ${{secrets.GITHUB_TOKEN}}
          #          column_id: '16739169'
