on:
  workflow_dispatch:

jobs:
  add_help_wanted_labels:
    runs-on: ubuntu-latest
    name: Add help wanted labels
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./add-label-to-cards/
        id: add-help-wanted-labels
        name: Add help wanted labels
        with:
          #          column_id: '16739169'
          column_name: 'To do'
          label_to_add: 'Help Wanted'
          project_name: 'Test'
          token: ${{secrets.GITHUB_TOKEN}}
