on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  add_help_wanted_labels:
    runs-on: ubuntu-latest
    name: Add help wanted labels
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./add-label-to-cards/
        id: add-help-wanted-labels
        name: Add help wanted labels
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label_to_add: 'Help Wanted'
          column_id: '16739169'
