on:
  workflow_dispatch:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    name: Manage Issue Labels
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./github-project-column-issue-labeler/
        id: manage-project-issue-labels
        name: Manage Project Issue Labels
        with:
          column_label_config: >  
            [
              {
                "columnName": "Name with whitespace ",
                "labelingRules": [
                  {
                    "action": "ADD ",
                    "labels": ["Duplicate Label", "New"]
                  },
                  {
                    "action": "ADD ",
                    "labels": ["DuplIcate LaBeL    ", "Help Wanted"]
                  },
                  {
                    "action": "ReMovE",
                    "labels": ["Duplicate emoji 🐌 ", "   Completed"]
                  },
                  {
                    "action": "ReMOVE",
                    "labels": ["DupliCAte Emoji 🐌", "Completed 1"]
                  }
                ]
              },
              {
                "columnName": "invalid column"
              }
            ]
          token: ${{secrets.GITHUB_TOKEN}}