on:
  workflow_dispatch:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    name: Manage Issue Labels
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./github-project-column-issue-labeler/
        id: manage-project-issue-labels
        name: Manage Project Issue Labels
        with:
          column_label_config: >
            [
              {
                "columnName": "Name",
                "labelingRules": []
              },
              {
                "columnName": "Name",
                "labelingRules": [
                  {
                  },
                  {
                    "action": "ADD"
                  },
                  {
                    "labels": ["a", "b", "c"]
                  },
                  {
                    "action": 3,
                    "labels": ["a", "b", "c"]
                  },
                  {
                    "action": "ADD",
                    "labels": {
                      "a": "a"
                    }
                  },
                  {
                    "action": "Unsupported Action",
                    "labels": ["a", "b", "c"]
                  }
                ]
              }
            ]
          token: ${{secrets.GITHUB_TOKEN}}
