on:
  workflow_dispatch:

jobs:
  on_deploy:
    runs-on: ubuntu-latest
    name: On Deploy
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - uses: ./on-deploy/
        id: on-deploy
        name: On Deploy
        with:
          project_name: "Test"
          token: ${{secrets.GITHUB_TOKEN}}
